name: Latest DEV Posts

on:
  schedule:
    - cron: "0 * * * *"   # Runs every hour
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: gautamkrishnar/blog-post-workflow@v1
        with:
          comment_tag_name: "DEVTO"
          feed_list: "https://dev.to/feed/ayush23chaudhary"

      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Update latest DEV posts"
